#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi7/ubi-minimal:7.9-1356@sha256:0aac6bc21ef99984241d2a9cffa651a75ac7567ade9d0f41e15878f5705b8267
