#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi7/ubi-minimal:7.9-1313@sha256:2bb01f6a9e5ab028d53af3c830926e287e5b83ecc4f4c0ac03d17aa263f7f7fb
