#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-896.1716497715@sha256:9e458f41ff8868ceae00608a6fff35b45fd8bbe967bf8655e5ab08da5964f4d0
