#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi7/ubi-minimal:7.9-1400@sha256:10dea3251dca3362ebacb4732dc26f550d92d56406a7f125977afbddaf7dec25
