#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-896.1717584414@sha256:5f1cd3422d5d46aea35dac80825dbcbd58213eef49c317f42a394345fb4e8ff1
