#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the template.

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1018@sha256:de2a0a20c1c3b39c3de829196de9694d09f97cd18fda1004de855ed2b4c841ba
